services:
  abyss-walker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: abyss-walker:latest
    stdin_open: true
    tty: true
    volumes:
      - abyss_walker_data:/data

volumes:
  abyss_walker_data:
